# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Debug Majora
bio: "Blogging about all things macOS security, threat intel, music, and more."

# twitter summary info
description: >-
  Debug Majora's blog.

# If it's an external image, set to true.
external-image: true
picture: https://avatars.githubusercontent.com/u/86309481?v=4

# Theme: true = dark, false = light, auto = follow system.
dark-theme: auto

baseurl: "" # user/organization pages repo => keep empty
url: "https://debug-majora.github.io" # set to https://debug-majora.github.io when ready

permalink: /:title/

twitter: debug_majora
github: debug-majora
email: 

authors:
  majora:
    name: Majora
    bio: "test bio"
    external-image: true
    picture: https://avatars.githubusercontent.com/u/86309481?v=4
    twitter: debug_majora

width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - vendor

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
